export const accountsTree = [
  {
    accountID: 4,
    accountCode: '1',
    nameAr: 'الاصول',
    nameEn: 'Assets',
    accountType: 'Asset',
    parentID: null,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.797',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 71,
    accountCode: '1001',
    nameAr: 'اصول طويلة الاجل',
    nameEn: '???? ????? ?????',
    accountType: 'Asset',
    parentID: 4,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.057',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 170,
    accountCode: '1001009',
    nameAr: 'اسهم مشتراه',
    nameEn: '???? ??????',
    accountType: 'Asset',
    parentID: 71,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.48',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 171,
    accountCode: '1001010',
    nameAr: 'اصول ثابتة',
    nameEn: '???? ?????',
    accountType: 'Asset',
    parentID: 71,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.483',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 72,
    accountCode: '1002',
    nameAr: 'الاصول المتداولة',
    nameEn: 'Assets ?????????',
    accountType: 'Asset',
    parentID: 4,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.06',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 172,
    accountCode: '1002001',
    nameAr: 'العملاء',
    nameEn: 'Customers',
    accountType: 'Asset',
    parentID: 72,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.49',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 173,
    accountCode: '1002002',
    nameAr: 'ارصده مدينه اخرى',
    nameEn: '????? ????? ????',
    accountType: 'Asset',
    parentID: 72,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.493',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 174,
    accountCode: '1002003',
    nameAr: 'ارصده مدينه مصالح وهيئات',
    nameEn: '????? ????? ????? ??????',
    accountType: 'Asset',
    parentID: 72,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.497',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 175,
    accountCode: '1002004',
    nameAr: 'مصروفات مدفوعه مقدما',
    nameEn: '??????? ?????? ?????',
    accountType: 'Asset',
    parentID: 72,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.503',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 176,
    accountCode: '1002007',
    nameAr: 'اوراق قبض',
    nameEn: '????? ???',
    accountType: 'Asset',
    parentID: 72,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.507',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 177,
    accountCode: '1002008',
    nameAr: 'نقديه بالصندوق والبنوك',
    nameEn: '????? ???????? ???????',
    accountType: 'Asset',
    parentID: 72,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.51',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 178,
    accountCode: '1002009',
    nameAr: 'سلف منفذة HR',
    nameEn: '??? ????? HR',
    accountType: 'Asset',
    parentID: 72,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.517',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 179,
    accountCode: '10021',
    nameAr: 'الصندوق',
    nameEn: 'Cash in Hand',
    accountType: 'Asset',
    parentID: 72,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.52',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 180,
    accountCode: '10022',
    nameAr: 'حسابات جاريه بالبنوك',
    nameEn: '?????? ????? ???????',
    accountType: 'Asset',
    parentID: 72,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.527',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 181,
    accountCode: '10026',
    nameAr: 'العملاء المباشرين',
    nameEn: 'Customers ?????????',
    accountType: 'Asset',
    parentID: 72,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.53',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 184,
    accountCode: '1002601',
    nameAr: 'ميدى كونسلت ادارة',
    nameEn: '???? ?????? ?????',
    accountType: 'Asset',
    parentID: 181,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.55',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 185,
    accountCode: '1002602',
    nameAr: 'ميدى كونسلت 1',
    nameEn: '???? ?????? 1',
    accountType: 'Asset',
    parentID: 181,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.553',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 186,
    accountCode: '1002604',
    nameAr: 'شركة مصرللـتأمين',
    nameEn: '???? ???????????',
    accountType: 'Asset',
    parentID: 181,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.56',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 187,
    accountCode: '1002605',
    nameAr: 'Allianz',
    nameEn: 'Allianz',
    accountType: 'Asset',
    parentID: 181,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.563',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 188,
    accountCode: '1002606',
    nameAr: 'Suez canel',
    nameEn: 'Suez canel',
    accountType: 'Asset',
    parentID: 181,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.57',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 189,
    accountCode: '1002607',
    nameAr: 'دلتا',
    nameEn: '????',
    accountType: 'Asset',
    parentID: 181,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.573',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 190,
    accountCode: '1002608',
    nameAr: 'الشركة الوطنية للتامين',
    nameEn: '?????? ??????? ???????',
    accountType: 'Asset',
    parentID: 181,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.577',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 182,
    accountCode: '10028',
    nameAr: 'عملاء متنوعون',
    nameEn: '????? ???????',
    accountType: 'Asset',
    parentID: 72,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.537',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 73,
    accountCode: '10031001',
    nameAr: 'العهد',
    nameEn: '?????',
    accountType: 'Asset',
    parentID: 4,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.063',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 74,
    accountCode: '10031002',
    nameAr: 'السلف',
    nameEn: '?????',
    accountType: 'Asset',
    parentID: 4,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.067',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 75,
    accountCode: '10031003',
    nameAr: 'خدمات طبيه للعاملين',
    nameEn: 'Services ???? ????????',
    accountType: 'Asset',
    parentID: 4,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.07',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 76,
    accountCode: '10031004',
    nameAr: 'تأمين لدى الغير',
    nameEn: 'Insurance ??? ?????',
    accountType: 'Asset',
    parentID: 4,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.077',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 77,
    accountCode: '10031006',
    nameAr: 'شركة إنماء للتمويل',
    nameEn: '???? ????? ???????',
    accountType: 'Asset',
    parentID: 4,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.08',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 78,
    accountCode: '10031007',
    nameAr: 'امانات شركة التأمين الطبى',
    nameEn: '?????? ???? ??????? ?????',
    accountType: 'Asset',
    parentID: 4,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.083',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 79,
    accountCode: '10031008',
    nameAr: 'شيكات تحت التحصيل',
    nameEn: '????? ??? ???????',
    accountType: 'Asset',
    parentID: 4,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.087',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 80,
    accountCode: '10031009',
    nameAr: 'شركات تأمين',
    nameEn: '????? Insurance',
    accountType: 'Asset',
    parentID: 4,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.09',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 81,
    accountCode: '10031010',
    nameAr: 'شركات شقيقه',
    nameEn: '????? ?????',
    accountType: 'Asset',
    parentID: 4,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.093',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 82,
    accountCode: '10031011',
    nameAr: 'شركه قناة السويس للتأمين',
    nameEn: '???? ???? ?????? ???????',
    accountType: 'Asset',
    parentID: 4,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.097',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 83,
    accountCode: '10031012',
    nameAr: 'المطالبات',
    nameEn: '?????????',
    accountType: 'Asset',
    parentID: 4,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.103',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 84,
    accountCode: '10031013',
    nameAr: 'مساهمات',
    nameEn: '???????',
    accountType: 'Asset',
    parentID: 4,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.11',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 85,
    accountCode: '10031014',
    nameAr: 'شركة خصم للخدمات الطبية',
    nameEn: '???? ??? ??????? ??????',
    accountType: 'Asset',
    parentID: 4,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.113',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 86,
    accountCode: '10032',
    nameAr: 'اسكان',
    nameEn: '?????',
    accountType: 'Asset',
    parentID: 4,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.117',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 183,
    accountCode: '10032001',
    nameAr: 'ضرائب ارباح تجاريه وصناعيه',
    nameEn: 'Taxes ????? ?????? ???????',
    accountType: 'Asset',
    parentID: 86,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.543',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 191,
    accountCode: '1232121',
    nameAr: 'ثضص',
    nameEn: 'ssss',
    accountType: 'ewew',
    parentID: 4,
    isActive: true,
    createdBy: 'ssd',
    createdAt: '2026-01-26T09:41:04.087',
    lastUpdatedBy: 'ssd',
    lastUpdatedAt: '2026-01-26T09:41:38.257',
  },
  {
    accountID: 5,
    accountCode: '2',
    nameAr: 'الخصوم',
    nameEn: 'Liabilities',
    accountType: 'Liability',
    parentID: null,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.81',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 87,
    accountCode: '2082',
    nameAr: 'خصوم متداولة',
    nameEn: '???? ???????',
    accountType: 'Liability',
    parentID: 5,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.12',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 88,
    accountCode: '2083',
    nameAr: 'خصوم طويلة الاجل',
    nameEn: '???? ????? ?????',
    accountType: 'Liability',
    parentID: 5,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.123',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 89,
    accountCode: '2121',
    nameAr: 'Mahmood',
    nameEn: 'Mahmood',
    accountType: 'Liability',
    parentID: 5,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.13',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 194,
    accountCode: '2432',
    nameAr: 'صثقص',
    nameEn: '4234',
    accountType: '4',
    parentID: null,
    isActive: true,
    createdBy: 'صثقصث',
    createdAt: '2026-01-26T13:27:04.68',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 3,
    accountCode: '24323',
    nameAr: 'dfds',
    nameEn: 'sdfs',
    accountType: '1',
    parentID: null,
    isActive: true,
    createdBy: 'ms',
    createdAt: '2026-01-25T08:46:13.433',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 6,
    accountCode: '3',
    nameAr: 'حقوق الملكية',
    nameEn: '???? ???????',
    accountType: 'Equity',
    parentID: null,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.81',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 90,
    accountCode: '3001',
    nameAr: 'رأس المال',
    nameEn: '??? ?????',
    accountType: 'Equity',
    parentID: 6,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.133',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 91,
    accountCode: '3008',
    nameAr: 'جارى حقوق المساهمين',
    nameEn: '???? ???? ?????????',
    accountType: 'Equity',
    parentID: 6,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.137',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 92,
    accountCode: '3015',
    nameAr: 'احتياطى قانونى',
    nameEn: '??????? ??????',
    accountType: 'Equity',
    parentID: 6,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.14',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 93,
    accountCode: '3016',
    nameAr: 'الارباح المرحله',
    nameEn: 'Profits ???????',
    accountType: 'Equity',
    parentID: 6,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.143',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 94,
    accountCode: '3017',
    nameAr: 'مصروفات سنوات سابقه',
    nameEn: '??????? ????? ?????',
    accountType: 'Equity',
    parentID: 6,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.147',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 95,
    accountCode: '3018',
    nameAr: 'مرحل عام 2021',
    nameEn: '???? ??? 2021',
    accountType: 'Equity',
    parentID: 6,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.153',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 96,
    accountCode: '3019',
    nameAr: 'مرحل عام 2022',
    nameEn: '???? ??? 2022',
    accountType: 'Equity',
    parentID: 6,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.157',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 97,
    accountCode: '3020',
    nameAr: 'مرحل عام 2023',
    nameEn: '???? ??? 2023',
    accountType: 'Equity',
    parentID: 6,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.16',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 98,
    accountCode: '3021',
    nameAr: 'مرحل عام 2024',
    nameEn: '???? ??? 2024',
    accountType: 'Equity',
    parentID: 6,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.167',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 7,
    accountCode: '4',
    nameAr: 'صافى الايرادات',
    nameEn: 'Net Revenue',
    accountType: 'Revenue',
    parentID: null,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.813',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 99,
    accountCode: '4002',
    nameAr: 'ايرادات التشغيل',
    nameEn: '??????? ???????',
    accountType: 'Revenue',
    parentID: 7,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.17',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 100,
    accountCode: '4003',
    nameAr: 'خصم مسموح بة',
    nameEn: '??? ????? ??',
    accountType: 'Revenue',
    parentID: 7,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.173',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 8,
    accountCode: '5',
    nameAr: 'تكلفة الايراد',
    nameEn: 'Cost ???????',
    accountType: 'Expense',
    parentID: null,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.817',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 101,
    accountCode: '5001',
    nameAr: 'اتعاب ادارية للغير',
    nameEn: '????? Administrative ?????',
    accountType: 'Expense',
    parentID: 8,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.177',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 9,
    accountCode: '6',
    nameAr: 'المصاريف الادارية والعمومية',
    nameEn: 'Expenses ???????? ?????????',
    accountType: 'Expense',
    parentID: null,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.82',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 102,
    accountCode: '6001',
    nameAr: 'عموله تحصيل ا',
    nameEn: 'Commission ????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.183',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 103,
    accountCode: '6002',
    nameAr: 'م بنكيه أ',
    nameEn: '? Banking ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.19',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 104,
    accountCode: '6003',
    nameAr: 'اجور أ',
    nameEn: 'Wages ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.193',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 105,
    accountCode: '6004',
    nameAr: 'مصروف تأمينات أ',
    nameEn: '????? ??????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.197',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 106,
    accountCode: '6005',
    nameAr: 'خدمات عاملين أ',
    nameEn: 'Services Employees ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.203',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 107,
    accountCode: '6006',
    nameAr: 'متنوعه أ',
    nameEn: '?????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.207',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 108,
    accountCode: '6007',
    nameAr: 'خدمات مؤداه من الغير أ',
    nameEn: 'Services ????? ?? ????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.21',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 109,
    accountCode: '6008',
    nameAr: 'نقل أ',
    nameEn: '??? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.213',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 110,
    accountCode: '6010',
    nameAr: 'صيانه مرافق أ',
    nameEn: 'Maintenance Utilities ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.22',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 111,
    accountCode: '6011',
    nameAr: 'صيانه أصول أ',
    nameEn: 'Maintenance ???? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.223',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 112,
    accountCode: '6013',
    nameAr: 'نت أ',
    nameEn: '?? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.227',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 113,
    accountCode: '6014',
    nameAr: 'اشتراكات أ',
    nameEn: '???????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.23',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 114,
    accountCode: '6015',
    nameAr: 'دعايه واعلان أ',
    nameEn: 'Advertising ?????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.237',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 115,
    accountCode: '6017',
    nameAr: 'بريد أ',
    nameEn: 'Post ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.24',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 116,
    accountCode: '6020',
    nameAr: 'كهرباء أ',
    nameEn: '?????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.243',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 117,
    accountCode: '6022',
    nameAr: 'غاز أ',
    nameEn: '??? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.25',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 118,
    accountCode: '6023',
    nameAr: 'رسوم أ',
    nameEn: 'Fees ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.253',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 119,
    accountCode: '6024',
    nameAr: 'أ.كتابيه أ',
    nameEn: '?.?????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.257',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 120,
    accountCode: '6026',
    nameAr: 'الاكراميات أ',
    nameEn: '?????????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.26',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 121,
    accountCode: '6027',
    nameAr: 'مستلزمات نظافة أ',
    nameEn: '???????? ????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.263',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 122,
    accountCode: '6028',
    nameAr: 'ضيافة أ',
    nameEn: '????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.27',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 123,
    accountCode: '6030',
    nameAr: 'فوائد مدينة أ',
    nameEn: '????? ????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.273',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 124,
    accountCode: '6031',
    nameAr: 'مكافأت أ',
    nameEn: '?????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.277',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 125,
    accountCode: '6032',
    nameAr: 'اتعاب محاسبين أ',
    nameEn: '????? ??????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.28',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 126,
    accountCode: '6033',
    nameAr: 'اتعاب و استشارات أ',
    nameEn: '????? ? ???????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.287',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 127,
    accountCode: '6035',
    nameAr: 'مستلزمات كمبيوتر أ',
    nameEn: '???????? ??????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.29',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 128,
    accountCode: '6038',
    nameAr: 'نظافة أ',
    nameEn: '????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.293',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 129,
    accountCode: '6039',
    nameAr: 'تدريب أ',
    nameEn: '????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.297',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 130,
    accountCode: '6040',
    nameAr: 'مستلزمات كهربائية أ',
    nameEn: '???????? ???????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.3',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 131,
    accountCode: '6041',
    nameAr: 'ادوات كتابيه أ',
    nameEn: '????? ?????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.307',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 132,
    accountCode: '6042',
    nameAr: 'صيانة الات أ',
    nameEn: '????? ???? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.31',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 133,
    accountCode: '6043',
    nameAr: 'صيانه كمبيوتر أ',
    nameEn: 'Maintenance ??????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.313',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 134,
    accountCode: '6044',
    nameAr: 'ايجار ماكينه تصوير أ',
    nameEn: '????? ?????? ????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.32',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 135,
    accountCode: '6046',
    nameAr: 'مصاريف جراج أ',
    nameEn: '?????? ???? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.323',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 136,
    accountCode: '6048',
    nameAr: 'الضرائب العقارية',
    nameEn: '??????? ????????',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.33',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 137,
    accountCode: '6049',
    nameAr: 'مياه أ',
    nameEn: '???? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.333',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 138,
    accountCode: '6050',
    nameAr: 'غرامات أ',
    nameEn: '?????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.34',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 139,
    accountCode: '6051',
    nameAr: 'ايجار أ',
    nameEn: '????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.34',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 140,
    accountCode: '6052',
    nameAr: 'تأمين مخاطر عدم سداد',
    nameEn: 'Insurance ????? ??? ????',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.347',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 141,
    accountCode: '6053',
    nameAr: 'صندوق اعانات الطوارئ',
    nameEn: '????? ?????? ???????',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.35',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 142,
    accountCode: '6054',
    nameAr: 'الاهلاك أ',
    nameEn: '??????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.353',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 143,
    accountCode: '6055',
    nameAr: 'مساهمة تكافلبة',
    nameEn: '?????? ???????',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.36',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 144,
    accountCode: '6056',
    nameAr: 'اتعاب مهنبة أ',
    nameEn: '????? ????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.363',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 145,
    accountCode: '6057',
    nameAr: 'ضريبة الدخل',
    nameEn: '????? ?????',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.37',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 146,
    accountCode: '6058',
    nameAr: 'تعبئة وتغليف أ',
    nameEn: '????? ?????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.373',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 147,
    accountCode: '6059',
    nameAr: 'فوائد الاهلى الكويتى',
    nameEn: '????? ?????? ???????',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.377',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 148,
    accountCode: '6060',
    nameAr: 'تامينات اجتماعية أ',
    nameEn: '??????? ???????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.38',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 149,
    accountCode: '6061',
    nameAr: 'تليفون أ',
    nameEn: '?????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.387',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 150,
    accountCode: '6062',
    nameAr: 'مطبوعات أ',
    nameEn: '??????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.39',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 151,
    accountCode: '6063',
    nameAr: 'خدمه رسائل الواتس اب أ',
    nameEn: '???? ????? ?????? ?? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.393',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 152,
    accountCode: '6064',
    nameAr: 'أنتقال أ',
    nameEn: '?????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.397',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 153,
    accountCode: '6065',
    nameAr: 'عموله أ',
    nameEn: 'Commission ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.4',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 154,
    accountCode: '6066',
    nameAr: 'توصيل خدمات طبيه أ',
    nameEn: '????? Services ???? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.407',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 155,
    accountCode: '6067',
    nameAr: 'احبار الكروت أ',
    nameEn: '????? ?????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.41',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 156,
    accountCode: '6068',
    nameAr: 'خدمات الايميل أ',
    nameEn: 'Services ??????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.413',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 157,
    accountCode: '6069',
    nameAr: 'إيجار مقر المهندسين',
    nameEn: '????? ??? ?????????',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.42',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 158,
    accountCode: '6070',
    nameAr: 'تليفون الخط الساخن أ',
    nameEn: '?????? ???? ?????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.42',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 159,
    accountCode: '6071',
    nameAr: 'ايجار ماسح ضوئى',
    nameEn: '????? ???? ????',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.427',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 160,
    accountCode: '6072',
    nameAr: 'تسويق',
    nameEn: '?????',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.43',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 161,
    accountCode: '6073',
    nameAr: 'كول سنتر',
    nameEn: '??? ????',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.437',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 162,
    accountCode: '6074',
    nameAr: 'تأمين أ',
    nameEn: 'Insurance ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.44',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 163,
    accountCode: '6075',
    nameAr: 'فوائد قرض بنك اسكندرية',
    nameEn: '????? ??? ??? ????????',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.447',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 164,
    accountCode: '6076',
    nameAr: 'مصروفات اخرى',
    nameEn: '??????? ????',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.45',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 165,
    accountCode: '6077',
    nameAr: 'صيانه ا',
    nameEn: 'Maintenance ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.457',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 166,
    accountCode: '6078',
    nameAr: 'اجور الاداره الماليه أ',
    nameEn: 'Wages ??????? ??????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.46',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 167,
    accountCode: '6079',
    nameAr: 'فوائد بنك القاهرة أ',
    nameEn: '????? ??? ??????? ?',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.467',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 168,
    accountCode: '6080',
    nameAr: 'ايجار برنامج',
    nameEn: '????? ??????',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.47',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 169,
    accountCode: '6081',
    nameAr: 'اتعاب مراقب الحسابات',
    nameEn: '????? ????? ????????',
    accountType: 'Expense',
    parentID: 9,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.473',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 10,
    accountCode: '7',
    nameAr: 'ايرادات اخرى',
    nameEn: '??????? ????',
    accountType: 'Expense',
    parentID: null,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.82',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 11,
    accountCode: '7001',
    nameAr: 'اجور',
    nameEn: 'Wages',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.83',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 12,
    accountCode: '7003',
    nameAr: 'دعايه واعلان',
    nameEn: 'Advertising ??????',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.833',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 13,
    accountCode: '7017',
    nameAr: 'خدمات طبية خاصة',
    nameEn: 'Services ???? ????',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.837',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 14,
    accountCode: '7019',
    nameAr: 'صيانه كمبيوتر',
    nameEn: 'Maintenance ???????',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.84',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 15,
    accountCode: '7020',
    nameAr: 'اتعاب أطباء (استشاره )',
    nameEn: '????? ????? (??????? )',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.843',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 16,
    accountCode: '7022',
    nameAr: 'بريد',
    nameEn: 'Post',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.847',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 17,
    accountCode: '7023',
    nameAr: 'كهرباء',
    nameEn: '??????',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.85',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 18,
    accountCode: '7024',
    nameAr: 'مكافأة',
    nameEn: '??????',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.857',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 19,
    accountCode: '7025',
    nameAr: 'متنوعه',
    nameEn: '??????',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.86',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 20,
    accountCode: '7026',
    nameAr: 'خسائر تشغيل',
    nameEn: '????? ?????',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.86',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 21,
    accountCode: '7027',
    nameAr: 'مصروفات تشغيل فاركو',
    nameEn: '??????? ????? ?????',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.867',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 22,
    accountCode: '7029',
    nameAr: 'مصروفات تشغيل اشتيجر طابا',
    nameEn: '??????? ????? ?????? ????',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.87',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 23,
    accountCode: '7030',
    nameAr: 'مصروفات تشغيل باى موب 0351',
    nameEn: '??????? ????? ??? ??? 0351',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.873',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 24,
    accountCode: '7031',
    nameAr: 'مصروفات تشغيل اكسبت 0351',
    nameEn: '??????? ????? ????? 0351',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.877',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 25,
    accountCode: '7032',
    nameAr: 'مصروفات تشغيل دومتى 0352',
    nameEn: '??????? ????? ????? 0352',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.88',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 26,
    accountCode: '7033',
    nameAr: 'مصروفات تشغيل البرج Staff 0361',
    nameEn: '??????? ????? ????? Staff 0361',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.883',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 27,
    accountCode: '7034',
    nameAr: 'مصروفات تشغيل بولمان شرم 0353',
    nameEn: '??????? ????? ?????? ??? 0353',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.887',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 28,
    accountCode: '7035',
    nameAr: 'مصروفات تشغيل نوفتيل شرم الشيخ 0358',
    nameEn: '??????? ????? ?????? ??? ????? 0358',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.89',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 29,
    accountCode: '7036',
    nameAr: 'مصروفات تشغيل نوفتيل مرسى علم 0356',
    nameEn: '??????? ????? ?????? ???? ??? 0356',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.893',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 30,
    accountCode: '7037',
    nameAr: 'مصروفات تشغيل Steigenberger Taba Hotel 0354',
    nameEn: '??????? ????? Steigenberger Taba Hotel 0354',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.9',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 31,
    accountCode: '7038',
    nameAr: 'مصروفات تشغيل مريكيور الغردقة عقد 0345',
    nameEn: '??????? ????? ??????? ??????? ??? 0345',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.907',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 32,
    accountCode: '7039',
    nameAr: 'مصروفات تشغبل ابو ظبى 0362',
    nameEn: '??????? ????? ??? ??? 0362',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.91',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 33,
    accountCode: '7040',
    nameAr: 'مصروفات تشغيل نوفتيل البرج مديرين 357',
    nameEn: '??????? ????? ?????? ????? ?????? 357',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.913',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 34,
    accountCode: '7041',
    nameAr: 'مصروفات تشغيل الجلالة 0365',
    nameEn: '??????? ????? ??????? 0365',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.917',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 35,
    accountCode: '7042',
    nameAr: 'مصروفات تشغيل ميركيور اسماعيلية 0355',
    nameEn: '??????? ????? ??????? ????????? 0355',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.92',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 36,
    accountCode: '7043',
    nameAr: 'مصروفات تشغيل دومتى 0366',
    nameEn: '??????? ????? ????? 0366',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.923',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 37,
    accountCode: '7044',
    nameAr: 'مصروفات تشغيل مريكيور الغردقة عقد 0360',
    nameEn: '??????? ????? ??????? ??????? ??? 0360',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.927',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 38,
    accountCode: '7045',
    nameAr: 'مصروفات تشغيل موفنبيك شرم عقد 0359',
    nameEn: '??????? ????? ??????? ??? ??? 0359',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.93',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 39,
    accountCode: '7046',
    nameAr: 'مصروفات تشغيل بولمان شرم 0367',
    nameEn: '??????? ????? ?????? ??? 0367',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.937',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 40,
    accountCode: '7047',
    nameAr: 'مصروفات تشغيل Steigenberger Taba Hotel 0368',
    nameEn: '??????? ????? Steigenberger Taba Hotel 0368',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.94',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 41,
    accountCode: '7048',
    nameAr: 'مصروفات تشغيل شركه عربيه للتنميه والتطوير العمران 0369',
    nameEn: '??????? ????? ???? ????? ??????? ???????? ??????? 0369',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.943',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 42,
    accountCode: '7049',
    nameAr: 'مصروفات تشغيل شركه صن سيتى للمقاولات 0370',
    nameEn: '??????? ????? ???? ?? ???? ????????? 0370',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.947',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 43,
    accountCode: '7050',
    nameAr: 'مصروفات تشغيل Mercure Hurghada Hotel 375',
    nameEn: '??????? ????? Mercure Hurghada Hotel 375',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.95',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 44,
    accountCode: '7051',
    nameAr: 'مصروفات تشغيل Mercure Ismailia Hotel371',
    nameEn: '??????? ????? Mercure Ismailia Hotel371',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.953',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 45,
    accountCode: '7052',
    nameAr: 'مصروفات نشغيل Novotel Marsa Alam Hotel 373',
    nameEn: '??????? ????? Novotel Marsa Alam Hotel 373',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.957',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 46,
    accountCode: '7053',
    nameAr: 'مصروفات تشغيل Novotel sharm El sheikh Staff 0377',
    nameEn: '??????? ????? Novotel sharm El sheikh Staff 0377',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.96',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 47,
    accountCode: '7054',
    nameAr: 'مصروفات تشغيل Novotel sharm El sheikh Managers 0376',
    nameEn: '??????? ????? Novotel sharm El sheikh Managers 0376',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.963',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 48,
    accountCode: '7055',
    nameAr: 'مصروفات تشغيل Abu Dhabi Tourist Investment Company0374',
    nameEn: '??????? ????? Abu Dhabi Tourist Investment Company0374',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.97',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 49,
    accountCode: '7056',
    nameAr: 'مصروفات تشغيل 0372 بورت غالب ريزورت CO -2153',
    nameEn: '??????? ????? 0372 ???? ???? ?????? CO -2153',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.973',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 50,
    accountCode: '7057',
    nameAr: 'مصروفات تشغيل 0378-CO 2162 فريدال للصناعات العطريه',
    nameEn: '??????? ????? 0378-CO 2162 ?????? ???????? ???????',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.977',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 51,
    accountCode: '7058',
    nameAr: 'مصروفات تشغيل دومتى 2163',
    nameEn: '??????? ????? ????? 2163',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.98',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 52,
    accountCode: '7059',
    nameAr: "'مصروفات تشغيل الجلالة -2164",
    nameEn: "'??????? ????? ??????? -2164",
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.983',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 53,
    accountCode: '7060',
    nameAr: 'مصروفات تشغيل بولمان staff شرم 2166',
    nameEn: '??????? ????? ?????? staff ??? 2166',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.987',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 54,
    accountCode: '7061',
    nameAr: 'مصروفات تشغيل بولمان شرم- وطنية 2165',
    nameEn: '??????? ????? ?????? ???- ????? 2165',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.99',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 55,
    accountCode: '7062',
    nameAr: 'مصروفات تشغيل ماي جاس CO-2169',
    nameEn: '??????? ????? ??? ??? CO-2169',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.993',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 56,
    accountCode: '7063',
    nameAr: 'مصروفات تشغيل سيوه للتصنيع والتنميه CO-2170',
    nameEn: '??????? ????? ???? ??????? ???????? CO-2170',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:05.997',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 57,
    accountCode: '7064',
    nameAr: 'ايراد خصم ادارة فنية',
    nameEn: '????? ??? ????? ????',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 58,
    accountCode: '7065',
    nameAr: 'خصم مكتسب',
    nameEn: '??? ?????',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.007',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 59,
    accountCode: '7066',
    nameAr: 'خصم مكتسب - تعاقدات',
    nameEn: '??? ????? - ???????',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.01',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 60,
    accountCode: '7067',
    nameAr: 'مصروفات تشغيل Mercure Ismailia Hotel2172',
    nameEn: '??????? ????? Mercure Ismailia Hotel2172',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.013',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 61,
    accountCode: '7068',
    nameAr: 'مصروفات تشغيل بورت غالب ريزورت CO -2173',
    nameEn: '??????? ????? ???? ???? ?????? CO -2173',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.017',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 62,
    accountCode: '7069',
    nameAr: 'مصروفات تشغيل Mercure Hurghada Hotel -2174',
    nameEn: '??????? ????? Mercure Hurghada Hotel -2174',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.02',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 63,
    accountCode: '7070',
    nameAr: '7070-مصروفات تشغيل Abu Dhabi Tourist Investment Company2175',
    nameEn: '7070-??????? ????? Abu Dhabi Tourist Investment Company2175',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.023',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 64,
    accountCode: '7071',
    nameAr: 'مصروفات تشغيل الجلالة عقد - 175',
    nameEn: '??????? ????? ??????? ??? - 175',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.027',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 65,
    accountCode: '7072',
    nameAr: 'مصروفات تشغيل دومتى - 174',
    nameEn: '??????? ????? ????? - 174',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.033',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 66,
    accountCode: '7073',
    nameAr: 'اتعاب التمريض',
    nameEn: '????? ???????',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.037',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 67,
    accountCode: '71',
    nameAr: 'فوائد دائنة',
    nameEn: '????? ?????',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.04',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 68,
    accountCode: '72',
    nameAr: 'عمولة من موردين',
    nameEn: '????? ?? Suppliers',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.043',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 69,
    accountCode: '74',
    nameAr: 'خصم مكتسب -مراجعه فنية',
    nameEn: '??? ????? -?????? ????',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.047',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    accountID: 70,
    accountCode: '75',
    nameAr: 'ايرادات متنوعة',
    nameEn: '??????? ??????',
    accountType: 'Expense',
    parentID: 10,
    isActive: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T14:13:06.053',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
];

export const costTree = [
  {
    costCenterID: 1,
    ccCode: '100',
    nameAr: 'مراكز التكلفة الرئيسية',
    nameEn: 'Main Cost Centers',
    parentID: null,
    isActive: true,
    isFinal: false,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.37',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 2,
    ccCode: '110',
    nameAr: 'الإدارة العامة والخدمات',
    nameEn: 'General & Admin Services',
    parentID: 1,
    isActive: true,
    isFinal: false,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.43',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 5,
    ccCode: '111',
    nameAr: 'إدارة الموارد البشرية',
    nameEn: 'Human Resources Dept',
    parentID: 2,
    isActive: true,
    isFinal: false,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.44',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 16,
    ccCode: '11101',
    nameAr: 'التوظيف والتدريب',
    nameEn: 'Recruitment & Training',
    parentID: 5,
    isActive: true,
    isFinal: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.487',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 17,
    ccCode: '11102',
    nameAr: 'الرواتب والمزايا',
    nameEn: 'Payroll & Benefits',
    parentID: 5,
    isActive: true,
    isFinal: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.49',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 6,
    ccCode: '112',
    nameAr: 'الإدارة المالية والمحاسبة',
    nameEn: 'Finance & Accounting Dept',
    parentID: 2,
    isActive: true,
    isFinal: false,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.447',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 18,
    ccCode: '11201',
    nameAr: 'حسابات العملاء',
    nameEn: 'Accounts Receivable',
    parentID: 6,
    isActive: true,
    isFinal: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.493',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 19,
    ccCode: '11202',
    nameAr: 'حسابات الموردين',
    nameEn: 'Accounts Payable',
    parentID: 6,
    isActive: true,
    isFinal: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.497',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 7,
    ccCode: '113',
    nameAr: 'إدارة تقنية المعلومات',
    nameEn: 'IT Department',
    parentID: 2,
    isActive: true,
    isFinal: false,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.45',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 20,
    ccCode: '11301',
    nameAr: 'صيانة الشبكات',
    nameEn: 'Network Maintenance',
    parentID: 7,
    isActive: true,
    isFinal: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.5',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 8,
    ccCode: '114',
    nameAr: 'الشؤون القانونية',
    nameEn: 'Legal Affairs',
    parentID: 2,
    isActive: true,
    isFinal: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.453',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 3,
    ccCode: '120',
    nameAr: 'العمليات والإنتاج',
    nameEn: 'Operations & Production',
    parentID: 1,
    isActive: true,
    isFinal: false,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.433',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 9,
    ccCode: '121',
    nameAr: 'وحدة الإنتاج (أ)',
    nameEn: 'Production Unit (A)',
    parentID: 3,
    isActive: true,
    isFinal: false,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.457',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 21,
    ccCode: '12101',
    nameAr: 'خط الإنتاج رقم 1',
    nameEn: 'Production Line 1',
    parentID: 9,
    isActive: true,
    isFinal: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.503',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 22,
    ccCode: '12102',
    nameAr: 'خط الإنتاج رقم 2',
    nameEn: 'Production Line 2',
    parentID: 9,
    isActive: true,
    isFinal: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.507',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 10,
    ccCode: '122',
    nameAr: 'وحدة الإنتاج (ب)',
    nameEn: 'Production Unit (B)',
    parentID: 3,
    isActive: true,
    isFinal: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.463',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 11,
    ccCode: '123',
    nameAr: 'مراقبة الجودة',
    nameEn: 'Quality Control',
    parentID: 3,
    isActive: true,
    isFinal: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.467',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 12,
    ccCode: '124',
    nameAr: 'المخازن والمستودعات',
    nameEn: 'Warehousing & Inventory',
    parentID: 3,
    isActive: true,
    isFinal: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.47',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 4,
    ccCode: '130',
    nameAr: 'التسويق والمبيعات',
    nameEn: 'Marketing & Sales',
    parentID: 1,
    isActive: true,
    isFinal: false,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.437',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 13,
    ccCode: '131',
    nameAr: 'فريق المبيعات المباشرة',
    nameEn: 'Direct Sales Team',
    parentID: 4,
    isActive: true,
    isFinal: false,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.473',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 23,
    ccCode: '13101',
    nameAr: 'مبيعات المنطقة الشرقية',
    nameEn: 'Eastern Region Sales',
    parentID: 13,
    isActive: true,
    isFinal: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.513',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 24,
    ccCode: '13102',
    nameAr: 'مبيعات المنطقة الغربية',
    nameEn: 'Western Region Sales',
    parentID: 13,
    isActive: true,
    isFinal: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.517',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 14,
    ccCode: '132',
    nameAr: 'الحملات الإعلانية',
    nameEn: 'Advertising Campaigns',
    parentID: 4,
    isActive: true,
    isFinal: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.477',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 15,
    ccCode: '133',
    nameAr: 'خدمة العملاء',
    nameEn: 'Customer Service',
    parentID: 4,
    isActive: true,
    isFinal: true,
    createdBy: 'msaad',
    createdAt: '2026-01-25T16:48:10.48',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
  {
    costCenterID: 27,
    ccCode: 'qw',
    nameAr: 'qwq',
    nameEn: 'qwq',
    parentID: null,
    isActive: true,
    isFinal: true,
    createdBy: 'eqwwq',
    createdAt: '2026-01-26T13:48:30.417',
    lastUpdatedBy: null,
    lastUpdatedAt: null,
  },
];
